# Generated by Django 3.2.6 on 2021-08-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
